default_language_version:
  python: python3.11

repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    - id: isort

  - repo: https://github.com/ambv/black
    rev: 23.10.1
    hooks:
    - id: black

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.4
    hooks:
    - id: ruff
      args: [--fix]

  - repo: https://github.com/myint/docformatter
    rev: v1.7.5
    hooks:
    - id: docformatter
      args: ["--config", "./pyproject.toml"]
      additional_dependencies: ['.[tomli]']

  - repo: https://github.com/python-poetry/poetry
    rev: 1.7.0
    hooks:
    - id: poetry-check
    - id: poetry-export
      args: ["-f", "requirements.txt", "-o", "requirements.txt", "--without-hashes"]
